# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clock.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clock(object):
    def setupUi(self, Clock):
        Clock.setObjectName("Clock")
        Clock.resize(694, 333)
        self.centralwidget = QtWidgets.QWidget(Clock)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 10, -1, 23)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.493, y1:0, x2:0.492925, y2:0.972, stop:0 rgba(24, 37, 54, 255), stop:1 rgba(81, 88, 100, 255));\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 651, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 215))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(170, 0, 255, 255), stop:0.00497512 rgba(197, 197, 147, 255), stop:1 rgba(163, 200, 165, 255));\n"
"\n"
"border-color:black;\n"
"border-width:3px;\n"
"border-style:solid;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_clock = QtWidgets.QLabel(self.frame_2)
        self.label_clock.setGeometry(QtCore.QRect(4, 3, 641, 131))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(77)
        self.label_clock.setFont(font)
        self.label_clock.setStyleSheet("background-color: transparent;\n"
"border-width:0px;\n"
"")
        self.label_clock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_clock.setObjectName("label_clock")
        self.label_date = QtWidgets.QLabel(self.frame_2)
        self.label_date.setGeometry(QtCore.QRect(10, 135, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_date.setFont(font)
        self.label_date.setStyleSheet("background-color: transparent;\n"
"border-width:0px;\n"
"")
        self.label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.label_saint = QtWidgets.QLabel(self.frame_2)
        self.label_saint.setGeometry(QtCore.QRect(10, 180, 631, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.label_saint.setFont(font)
        self.label_saint.setStyleSheet("background-color: transparent;\n"
"border-width:0px;\n"
"")
        self.label_saint.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saint.setObjectName("label_saint")
        self.label_shadow = QtWidgets.QLabel(self.frame_2)
        self.label_shadow.setGeometry(QtCore.QRect(5, 5, 641, 144))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(77)
        self.label_shadow.setFont(font)
        self.label_shadow.setStyleSheet("background-color: transparent;\n"
"border-width:0px;\n"
"")
        self.label_shadow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shadow.setObjectName("label_shadow")
        self.label_shadow.raise_()
        self.label_clock.raise_()
        self.label_date.raise_()
        self.label_saint.raise_()
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(570, 270, 87, 16))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setObjectName("label")
        self.pushButton_close = QtWidgets.QPushButton(self.frame)
        self.pushButton_close.setGeometry(QtCore.QRect(5, 7, 36, 28))
        self.pushButton_close.setStyleSheet("background-color: transparent;")
        self.pushButton_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icones/icones/standard/white/supprimer(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon)
        self.pushButton_close.setObjectName("pushButton_close")
        self.verticalLayout.addWidget(self.frame)
        Clock.setCentralWidget(self.centralwidget)

        self.retranslateUi(Clock)
        QtCore.QMetaObject.connectSlotsByName(Clock)

    def retranslateUi(self, Clock):
        _translate = QtCore.QCoreApplication.translate
        Clock.setWindowTitle(_translate("Clock", "Clock"))
        self.label_clock.setText(_translate("Clock", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt;\">12:34:</span><span style=\" font-size:48pt;  color:#5d5d5d;\">59</span></p></body></html>"))
        self.label_date.setText(_translate("Clock", "<html><head/><body><p align=\"center\"><span style=\" color:#3a3a3a;\">Lundi 24 décembre 2022</span></p></body></html>"))
        self.label_saint.setText(_translate("Clock", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic; color:#5a5a5a;\">St Patrick</span></p></body></html>"))
        self.label_shadow.setText(_translate("Clock", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; color:#d9d9d9;\">12:34:</span><span style=\" font-size:48pt; color:#d9d9d9;\">59</span></p></body></html>"))
        self.label.setText(_translate("Clock", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">by </span><span style=\" color:#8484c6;\">Xenatronics</span></p></body></html>"))
import clock_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Clock = QtWidgets.QMainWindow()
    ui = Ui_Clock()
    ui.setupUi(Clock)
    Clock.show()
    sys.exit(app.exec_())
